module.exports = {
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILED: 'GET_EVENTS_FAILED',
  CLEAR_REDUCER_EVENT: 'CLEAR_REDUCER_EVENT',
  GET_EVENT_SUCCESS: 'GET_EVENT_SUCCESS',
  GET_EVENT_FAILED: 'GET_EVENT_FAILED'
};
